### ISSUE TITLE
Reader SDK?

### ISSUE THREAD

**Issue by theopolisme** [SudoPlz/react-native-sp-reader-sdk#1]
Hi - is this Pay SDK what ultimately became the Reader SDK that was released a few weeks ago? https://docs.connect.squareup.com/payments/readersdk/quickstart

If so, did your company end up creating any updated React Native bindings for the final / new version of the SDK? If so it would be so awesome if you could release them so that we don't have to reinvent the wheel from scratch.

Thank you so much for open sourcing this project!!

**Comment by SudoPlz** [comment]
Hi @theopolisme yes, that's PaySDK that became Reader SDK and yes we did create updated React Native bindings. I'll upload them today.

**Comment by theopolisme** [comment]
Thanks so much! Looking forward to it. 👍

**Comment by SudoPlz** [comment]
@theopolisme Just uploaded all of our code.

I didn't test anything yet for this module, but we've been using the exact same code in production for a while now.

If something doesn't work on this specific repo, feel free to open a PR and I'll accept it.
