### ISSUE TITLE
package not install sucessfully because it is not available in NPM 

### ISSUE THREAD

**Issue by ektasahu027** [SudoPlz/react-native-sp-reader-sdk#2]
When i run npm install react-native-square-renderSDK  than i got an error 

> $ npm i react-native-square-readerSDK --save
> npm ERR! code E404
> npm ERR! 404 Not Found: react-native-square-readerSDK@latest
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\ekta.sahu\AppData\Roaming\npm-cache\_logs\2018-08-28T13_06_06_295Z-debug.log

**Comment by SudoPlz** [comment]
Right, can you try again with `npm install react-native-sp-reader-sdk --save`?

**Comment by ektasahu027** [comment]
thanks now it is install successfully. For linking only we have to run react-native-link command right? or we have to perform manual link here?

**Comment by SudoPlz** [comment]
You'll have to try `react-native link` which should work, but you might still need to do some manual work in case it doesn't. Try it and let me know if you take any extra steps so that we better document it.
