### ISSUE TITLE
Dependencies issues 

### ISSUE THREAD

**Issue by ektasahu027** [SudoPlz/react-native-sp-reader-sdk#3]
In renderSDK package build.gradle  i change implementation and runtimeOnly to compile beacause i got 
this error - 

> Could not find method implementation() for arguments [com.squareup.sdk.reader:reader-sdk-

after that when i clean the project i got some more Dependencies errors -

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-sp-reader-sdk'.
      > Could not resolve all dependencies for configuration ':react-native-sp-reader-sdk:_debugPublishCopy'.
         > Could not resolve com.squareup.sdk.reader:reader-sdk-null:1.0.1.
           Required by:
               nativeApp:react-native-sp-reader-sdk:unspecified
            > Could not resolve com.squareup.sdk.reader:reader-sdk-null:1.0.1.
               > Could not get resource 'https://sdk.squareup.com/android/com/squareup/sdk/reader/reader-sdk-null/1.0.1/reader-sdk-null-1.0.1.pom'.
                  > java.lang.NullPointerException (no error message)
         > Could not resolve com.squareup.sdk.reader:reader-sdk-internals:1.0.1.
           Required by:
               nativeApp:react-native-sp-reader-sdk:unspecified
            > Could not resolve com.squareup.sdk.reader:reader-sdk-internals:1.0.1.
               > Could not get resource 'https://sdk.squareup.com/android/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.pom'.
                  > java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by SudoPlz** [comment]
Right, so the reason this happens is because I forgot to add an extra step to the instructions, I just added it:

5. Go in ~/.gradle/gradle.properties and create 2 values:

```
SQUARE_REPO_USERNAME=WHATEVER_YOUR_SQUARE_USERNAME_IS
SQUARE_REPO_PASSWORD=WHATEVER_YOUR_SQUARE_PASSWORD_IS
```

That should fix it.
Try that and let me know if it worked.

**Comment by ektasahu027** [comment]
Thnaks i successfully add the package but i have a one question when i run link command than in MainApplication.java file add these two line show in below-

**Comment by ektasahu027** [comment]
I put

**Comment by ektasahu027** [comment]
As mentioned above I have update the credentials in project root folder-> android -> gradle.properties:

SQUARE_REPO_USERNAME= WHATEVER_YOUR_SQUARE_USERNAME_IS
SQUARE_REPO_PASSWORD= WHATEVER_YOUR_SQUARE_PASSWORD_IS
And still I am not able to run the project and getting below issues , could you please help me on this.

**FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find com.squareup.sdk.reader:reader-sdk-sq0idp-lajsldjfljal******:1.0.1.
  Searched in the following locations:
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/m2repository/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.pom
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/m2repository/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.jar
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/google/m2repository/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.pom
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/google/m2repository/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.jar
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/android/m2repository/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.pom
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/android/m2repository/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.jar
      file:/C:/Users/ekta.sahu/.m2/repository/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.pom
      file:/C:/Users/ekta.sahu/.m2/repository/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.jar
      https://jcenter.bintray.com/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.pom
      https://jcenter.bintray.com/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.jar
      file:/D:/Ekta_hiteshi/React_projects/Wolter_apps_details/nomad-truck-tablet/node_modules/react-native/android/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.pom
      file:/D:/Ekta_hiteshi/React_projects/Wolter_apps_details/nomad-truck-tablet/node_modules/react-native/android/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.jar
      https://maven.google.com/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.pom
      https://maven.google.com/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.jar
  Required by:
      project :app > project :react-native-sp-reader-sdk
> Could not find com.squareup.sdk.reader:reader-sdk-internals:1.0.1.
  Searched in the following locations:
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/m2repository/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.pom
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/m2repository/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.jar
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/google/m2repository/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.pom
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/google/m2repository/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.jar
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/android/m2repository/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.pom
      file:/C:/Users/ekta.sahu/AppData/Local/Android/Sdk/extras/android/m2repository/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.jar
      file:/C:/Users/ekta.sahu/.m2/repository/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.pom
      file:/C:/Users/ekta.sahu/.m2/repository/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.jar
      https://jcenter.bintray.com/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.pom
      https://jcenter.bintray.com/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.jar
      file:/D:/Ekta_hiteshi/React_projects/Wolter_apps_details/nomad-truck-tablet/node_modules/react-native/android/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.pom
      file:/D:/Ekta_hiteshi/React_projects/Wolter_apps_details/nomad-truck-tablet/node_modules/react-native/android/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.jar
      https://maven.google.com/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.pom
      https://maven.google.com/com/squareup/sdk/reader/reader-sdk-internals/1.0.1/reader-sdk-internals-1.0.1.jar
  Required by:
      project :app > project :react-native-sp-reader-sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s**


and I have more question when I run link command then in MainApplication.java file these two lines add as I show on below:

import com.reactlibrary.RCTACSquareSDKPackage;
new RCTACSquareSDKPackage(),

but you show in instructions for manual link in android to add below two lines:

import com.sudoplz.rnsquarereaderSDK.RNReactNativeSquarereaderSDKPackage;
new RNReactNativeSquarereaderSDKPackage(),
So I have to add both line or any one of them?
Thanks again!

**Comment by SudoPlz** [comment]
Hi  again @ektasahu027 , that was another old instructions issue. What was added automatically is the right class (RCTACSquareSDKPackage).

(RNReactNativeSquarereaderSDKPackage was the old name) I changed the readme to reflect that.

When it comes to the credentials issue (`Could not find com.squareup.sdk.reader:reader-sdk-sq0idp-lajsldjfljal******:1.0.1.`) are you sure you've specified the username in the right way?


i.e if your username is `foobaruser` the gradle property would be `SQUARE_REPO_USERNAME=foobaruser` with no spaces.

By the way this error is not specific to `react-native-sp-reader-sdk` but more relevant to readerSDK android installation in general, so feel free to read this https://docs.connect.squareup.com/payments/readersdk/setup-android

If you discover that something was missing from the instructions of this repo either open a PR to add it or let me know and I'll add it myself.

Also try to reach the reader SDK url in your browser to check if you got it right:

In your case it would be something like https://repo.jfrog.org/artifactory/libs-release-bintray/com/squareup/sdk/reader/reader-sdk-sq0idp-lajsldjfljal******/1.0.1/reader-sdk-sq0idp-lajsldjfljal******-1.0.1.jar

If it doesn't resolve to a file, you probably have the wrong credentials.

**Comment by ektasahu027** [comment]
Hi Sudo, thanks for the prompt reply.
Could you please let me know where I have to put Credentials , I mean exact location if you can share where I have put it,  For this I have little bit confusion to put it.
Currently I have update it in project root folder/android/gradle.properties file , May I doing put in right place?
Also I have correct credentials for square login. Thanks a lot.

**Comment by SudoPlz** [comment]
Oh right, so you're on windows. You'll have to place it in `C:\Users\{username}\.gradle\gradle.properties` instead of ` ~/.gradle/gradle.properties`

**Comment by ektasahu027** [comment]
Thanks Sudo i resolve that .jar files error but i got new error could you please help to solve this error:


FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':react-native-sp-reader-sdk:compileDebugAidl' property 'importDirs' during up-to-date check.
> The library com.google.android.gms:play-services-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 12.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Thanks

**Comment by SudoPlz** [comment]
You're probably using a package of`com.google.android.gms:play-services-base:15.0.1` somewhere.

ReaderSDK forces you to use 12.0.1 all over the project, thus you'll have to manually force the other dependencies to use 12.0.1 as well.

This is a known issue in square and they're working on a fix. We had to quit using firebase for now because of this.

A fix should be out from then very soon.
Until then use 12.0.1 and you'll be good to go

**Comment by ektasahu027** [comment]
Thanks Sudo,You are right, I am using this com.google.android.gms:play-services-base:11.6.0 package in my project build.gradle file and i change 11.6.0 to 12.0.1 but i am still getting same error- 

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':react-native-sp-reader-sdk:compileDebugAidl' property 'importDirs' during up-to-date check.
> The library com.google.android.gms:play-services-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 12.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

**and also i am working on new fresh demo project and in this i am only integrate your package but i am still getting errors which is package not exist -**

>  error: package com.sudoplz.rnsquarereaderSDK does not exist
> import com.sudoplz.rnsquarereaderSDK.RCTACSquareSDKPackage;
>                                     ^
> D:\Ekta_hiteshi\React_projects\MyNewApp\android\app\src\main\java\com\mynewapp\MainApplication.java:27: error: cannot find symbol
>           new RCTACSquareSDKPackage()
>               ^
>   symbol: class RCTACSquareSDKPackage
> 2 errors
> :app:compileDebugJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.

I checked every where like in settings.gradle and build.gradle the package successfully added but its not find this `import com.sudoplz.rnsquarereaderSDK.RCTACSquareSDKPackage; ` package now what I have do, Could you please help me on this.

**Comment by SudoPlz** [comment]
Ok I have a solution for both of the issues:


A) For the first problem, the issue is that you're using some library that requires play services version (I figured this out because I saw `[[15.0.1,15.0.1]]` in the error message) so you need **15.0.1**, NOT **12.0.1**.

The solution is:
- to use **15.0.1** everywhere

(i.e like this: `com.google.android.gms:play-services-base:15.0.1`)
note that you'll need to use 15.0.1 for every other com.google.android.gms dependency
(i.e
`com.google.android.gms:play-services-base`, 
 `com.google.android.gms:play-services-maps`, 
 `com.google.android.gms:play-services-places`, 
 `com.google.android.gms:play-services-location`, 
 `com.google.android.gms:play-services-gcm `
... etc if any of that exists in your project dependencies. (run `./android/gradlew -p app dependencies` if you wish to see what module of `com.google.android.gms` your project is using and what version)


- also you'll need to include this line in your dependencies (that's something I learned from Square 2 days ago):

`compile 'com.google.android.gms:play-services-safetynet:15.0.1'`



B) For the second issue (package not found) change:

`import com.sudoplz.rnsquarereaderSDK.RNReactNativeSquarereaderSDKPackage;`

with

`import com.sudoplz.rnsquarepaysdk.RNReactNativeSquarereaderSDKPackage;`

and it should work.

Try that and let me know if everything worked

**Comment by ektasahu027** [comment]
Hi Sudo, thanks for the solution. Now finally I successfully integrate the renderSDK package in my project for that i perform some changes in my project build.gradle files and your package build.gradle file also.
I'll show you what i do i simply add 
```
     implementation 'com.google.android.gms:play-services-base:15.0.1'
     implementation 'com.google.android.gms:play-services-safetynet:15.0.1'
```
these two lines in your package build.gradle file and In my build.gradle file i add multidex support with the help of 

```
 multiDexEnabled true
 implementation 'com.android.support:multidex:1.0.3'
```

these two files.

and one more thing which i do right now i am working on Window but i did't create gradle.propertices in C:\Users\{username}\.gradle\gradle.properties as you told because i am getting errors . I just add the username and password key in my project root gradle.propertices file and change 
```
  maven {
        credentials {
            // Set in ~/.gradle/gradle.properties (DON'T forget to set this)
            username getEnvValueForKey("SQUARE_REPO_USERNAME") // Repository username provided by Square
            password getEnvValueForKey("SQUARE_REPO_PASSWORD") // Repository password provided by Square
        }
        url "https://sdk.squareup.com/android"
    }
```
with
```
 maven {
            url "https://sdk.squareup.com/android"
            credentials {
                username SQUARE_READER_SDK_APPLICATION_ID
                password SQUARE_READER_SDK_REPOSITORY_PASSWORD
            }
        }
```
and i also past this code in my project root build.gradle.

Thank you.
