### ISSUE TITLE
Question: how to connect bluetooth readers?

### ISSUE THREAD

**Issue by aecorredor** [SudoPlz/react-native-sp-reader-sdk#4]
Hey man, this looks very promising. I have an idea for a POS app to provide a solution for certain retailers, but allow them to keep using their square hardware for payments. 

From reading the square Reader SDK overview, I see they allow you to connect bluetooth square devices.

Do you have any plans to support this? Or are you looking into it?

Anyway, thanks for creating this. Hope I can be of any help in the future. 

Cheers.

**Comment by SudoPlz** [comment]
I just wrap their sdk, and yeah connected Bluetooth devices do work already.
