### ISSUE TITLE
RenderSdk initialization problem.

### ISSUE THREAD

**Issue by ektasahu027** [SudoPlz/react-native-sp-reader-sdk#5]
Hi Sudo ,As you show in code. I am using same process i initialize the renderSdk using initSdk method and that method sucessfully initialize renderSdk but after initialization when i call authorizeWithCode method than it return me below error  

![image](https://user-images.githubusercontent.com/41745899/45282673-3858cc00-b4f9-11e8-8e10-90e94982498b.png)

Here is my code- 
```
 constructor(props) {
    super(props)
    const readerSdk  = new ReaderSDK();

     readerSdk.initSdk().then(() => {
      // success
      console.log("sucessfully initialize in renderSDK")  // i got success log.
    }).catch((err) => {
      // failure
      console.log("failed to initialize in renderSDK")
    })
   
      // login with an auth code
      readerSdk.authorizeWithCode("sq0acp-USbDArYu********-  _********").then(() => {
        // success
        console.log("sucessfully to authorizeWithCode")
      }).catch((err) => {
        // failure
        console.log("failed to authorizeWithCode")
      })
```

Could you please help me on that...

**Comment by SudoPlz** [comment]
I just came back from vocation, let me check this out and get back to you. Later today, or tomorrow you'll have my reply.

**Comment by SudoPlz** [comment]
Ok so the problem is you must follow [this step](https://github.com/SudoPlz/react-native-sp-reader-sdk/wiki/Step-3:-Android-Setup#3-initialise-the-sdk).

Specifically the `onCreate` part.
This will resolve the issue.

**Comment by ektasahu027** [comment]
Thanks SudePlz now its resolve...
