### ISSUE TITLE
Square ReaderSDK initialize issue in react-native

### ISSUE THREAD

**Issue by divsbhalala** [SudoPlz/react-native-sp-reader-sdk#7]
Hi Sudo ,As you show in code. I am using same process i initialize the renderSdk using initSdk method when i call authorizeWithCode method than it return me below error
```
Square Element Mobile token error Error: You haven't initialized paySDK. Run initSdk first.
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:398)
    at MessageQueue.js:137
    at MessageQueue.__guardSafe (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js:70
```
Here is code
```
const readerSdk = new ReaderSDK();
  readerSdk.initSdk();
  readerSdk.authorizeWithCode("mobileauthtoken").then((resp) => {
      console.log("Square Element Mobile token success", resp);
  }).catch((err) => {
      console.log("Square Element Mobile token error", err);
  });

```

**Comment by SudoPlz** [comment]
Repro repo --> https://github.com/divsbhalala/squareDemo

**Comment by SudoPlz** [comment]
The repro repo does not call any `react-native-sp-reader-sdk` methods anywhere. Also reader sdk doesn't look properly embedded looking into it now.

**Comment by SudoPlz** [comment]
Ok I fixed the repo (you can find it [here](https://github.com/SudoPlz/react-native-sp-reader-sdk-example))

The problem was that there's still one line missing from `AppDelegate.m`

```
  [SQRDReaderSDK initializeWithApplicationLaunchOptions:launchOptions];
```

Also updated the docs to make that clearer --> https://github.com/SudoPlz/react-native-sp-reader-sdk/wiki/Step-2:-iOS-Setup#add-a-reader-sdk-to-your-appdelegate
