### ISSUE TITLE
ACSquareSDK.SQRDAdditionalPaymentTypeManualCardEntry ios error.

### ISSUE THREAD

**Issue by ektasahu027** [SudoPlz/react-native-sp-reader-sdk#8]
Hi Sudo, readerSDK perfect run on android but when i run app in IOS than i am getting this error. i also download framework and and i follow all the instruction setup of ios which is given. 
![simulator screen shot - ipad air - 2018-09-28 at 19 09 02](https://user-images.githubusercontent.com/41745899/46212251-25e0ee00-c353-11e8-9535-9f3fd9c43fcc.png)

please help me on this.
Thank you.

**Comment by SudoPlz** [comment]
Hey @ektasahu027, I think you forgot a fullstop, so that the code looks like this:

`ReaderSDK.AdditionalPaymentTypes.MANUAL_CARD_ENTRY`

instead of 

`ReaderSDK.AdditionalPaymentTypesMANUAL_CARD_ENTRY`

**Comment by ektasahu027** [comment]
Where...

**Comment by SudoPlz** [comment]
right after `AdditionalPaymentTypes` and before `MANUAL_CARD_ENTRY`

**Comment by ektasahu027** [comment]
yeah, but could you please tell me at which file...

**Comment by SudoPlz** [comment]
Unfortunately no I can't because I don't have access to your project, search for it with your text editor.

**Comment by ektasahu027** [comment]
I searched in my text editor but no result found why?

**Comment by SudoPlz** [comment]
`¯\_(ツ)_/¯`
